# Generated by Django 4.2.1 on 2023-06-14 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_cancel', 'Can cancel Order')]},
        ),
    ]
